### PR TITLE
Support for Generic Tracker (Vive Tracker)

### PR DESCRIPTION
**Pull request by karlun**
The changes does two things for using the vrpn-openvr tool together with Vive Tracker, that appears as GenericTracker in openvr. First of all devices of the class GenericTracker will be handled like a controller. Second, the VRPN device name is changed to make it easier to know which device is which, also across computers and configurations. HMDs are named like before but controllers get the name "openvr/controller/left" and "openvr/controller/right" (respectively) while all other trackers are named after their serial id, e g "openvr/controller/LHR-1FD1E53".

### CODE REVIEW

**Comment by paperManu** [comment]
Hi Karlun,
Thanks for the contribution! We also added Vive Tracker support, but it was not mirrored on Github yet. Maybe you could check whether you have anything to add to our implementation?

**Comment by karlun** [comment]
Your work on adding the tracker support is more thorough and overshadows my first commit which only adds one single line :-), but at least our group need the change in VRPN tracker name (second commit). I can rebase my changes on your new commits if think that you and other will benefit from it also.

**Comment by ubald** [comment]
I like the idea of having the left/right and serial numbers. 
But I'm curious, how does it determine which is left and which is right? And what happens if we use more than two controllers (by pairing with a dongle)?

**Comment by karlun** [comment]
@ubald According to discussions on Reddit it seems to be based on how they are located relative to each other and the screen (which is defined in the room setup). In my code any controller that is not left or right at start-up is given name based on its serial id.

I believe, based on early tests, that a controller can change identity during execution and the question is what VRPN should do then. One thought is to use only serial id, and another is to serve the data under both names, and let the name "left" and "right" change device based on what the OpenVR system says.

**Comment by karlun** [comment]
Made a new pull request #2 for the VRPN names

**Pull request closed without merging**
